---
- name: ensure packages are installed
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - anacron
    - avahi-daemon
    - smartmontools

- name: enable smartmontools
  lineinfile:
    dest: /etc/default/smartmontools
    regexp: ^start_smartd
    line: start_smartd=yes
  notify:
    - restart smartmontools
