---
- name: add af_key kernel module to startup configuration
  copy:
    src: af_key.conf
    dest: /etc/modules-load.d/af_key.conf
    owner: root
    group: root
    mode: 0644
  notify:
  - run modprobe af_key

- name: configure grub for docker
  lineinfile:
    dest: /etc/default/grub
    regexp: ^GRUB_CMDLINE_LINUX=
    line: 'GRUB_CMDLINE_LINUX="cgroup_enable=memory swapaccount=1"'
  notify:
    - run update-grub
