---
# Openvpn tasks
- include_vars: secrets.yml
  no_log: true
- name: add apt key
  apt_key: url=https://swupdate.openvpn.net/repos/repo-public.gpg state=present
- name: add apt repository
  apt_repository: repo='deb http://swupdate.openvpn.net/apt trusty main' state=present
- name: ensure openvpn is installed
  apt: name=openvpn state=installed
- name: add system account openvpn
  user: name=openvpn comment="OpenVPN Account" createhome=no home=/nonexistent shell=/usr/sbin/nologin system=yes uid=999
- name: etc openvpn directory
  file: path=/etc/openvpn state=directory owner=openvpn group=openvpn mode=0755
- name: openvpn state and log files
  shell: sudo -u openvpn touch /etc/openvpn/{{ item }}
  args:
    creates: /etc/openvpn/{{ item }}
  with_items:
    - ipp-443-tcp.txt
    - ipp-443-udp.txt
    - openvpn-status-443-tcp.log
    - openvpn-status-443-udp.log
- name: openvpn configuration files
  copy: src=openvpn/{{ item.name }} dest=/etc/openvpn/{{ item.name }} owner=openvpn group=openvpn mode={{ item.mode }}
  notify:
    - restart openvpn
  with_items:
    - { name: 'ca-clients.crt', mode: '0644' }
    - { name: 'dh2048.pem', mode: '0644' }
    - { name: 'nat2.crt', mode: '0644' }
    - { name: 'server-443-tcp.conf', mode: '0640' }
    - { name: 'server-443-udp.conf', mode: '0640' }
- name: openvpn crl for clients secret file
  copy: content="{{ crl_clients_pem }}" dest=/etc/openvpn/crl-clients.pem owner=openvpn group=openvpn mode=0600
  notify:
    - restart openvpn
- name: openvpn nat2 private key secret file
  copy: content="{{ nat2_key }}" dest=/etc/openvpn/nat2.key owner=openvpn group=openvpn mode=0600
  notify:
    - restart openvpn
- name: openvpn ta key secret file
  copy: content="{{ ta_key }}" dest=/etc/openvpn/ta.key owner=openvpn group=openvpn mode=0600
  notify:
    - restart openvpn
- name: delete old files
  file: dest=/etc/openvpn/{{ item }} state=absent
  notify:
    - restart openvpn
  with_items:
    - server-1194-udp.conf
    - ccd
- name: rc.local to execute configure-pat.sh
  copy: src=rc.local dest=/etc/rc.local owner=root group=root mode=0755
- name: add file configure-pat.sh
  copy: src=configure-pat.sh dest=/usr/local/bin owner=root group=root mode=0755
