---
- include_vars: vault.yml
  no_log: true
- name: ensure openvpn is installed
  apt:
    name: openvpn
    state: installed
- name: add system account openvpn
  user:
    name: openvpn
    comment: "OpenVPN Account"
    createhome: no
    home: /nonexistent
    shell: /usr/sbin/nologin
    system: yes
    uid: 999
- name: etc openvpn directory
  file:
    path: /etc/openvpn
    state: directory
    owner: openvpn
    group: openvpn
    mode: 0755
- name: openvpn state files
  shell: sudo -u openvpn touch /etc/openvpn/ipp-443-udp.txt
  args:
    creates: /etc/openvpn/ipp-443-udp.txt
    warn: false
- name: openvpn certs
  copy:
    src: openvpn/{{ item }}
    dest: /etc/openvpn/{{ item }}
    owner: openvpn
    group: openvpn
    mode: 0644
  notify:
    - restart openvpn
  with_items:
    - ca.crt
    - dh4096.pem
    - server.crt
- name: openvpn configuration files
  copy:
    src: openvpn/server-443-udp.conf
    dest: /etc/openvpn/server-443-udp.conf
    owner: openvpn
    group: openvpn
    mode: 0640
  notify:
    - restart openvpn
- name: openvpn private keys
  copy:
    content: "{{ item.content }}"
    dest: /etc/openvpn/{{ item.name }}
    owner: openvpn
    group: openvpn
    mode: 0600
  notify:
    - restart openvpn
  with_items:
    - { name: crl.pem,    content: "{{ crl_pem }}" }
    - { name: server.key, content: "{{ server_key }}" }
    - { name: ta.key,     content: "{{ ta_key }}" }
- name: rc.local to execute configure-pat.sh
  copy:
    src: rc.local
    dest: /etc/rc.local
    owner: root
    group: root
    mode: 0755
- name: add file configure-pat.sh
  copy:
    src: configure-pat.sh
    dest: /usr/local/bin
    owner: root
    group: root
    mode: 0755
- name: ensure systemd file openvpn@.service has the correct entry
  ini_file:
    dest: /lib/systemd/system/openvpn@.service
    no_extra_spaces: yes
    section: Unit
    option: After
    value: 'network.target network-online.target'
