---
- hosts: openvpn
  remote_user: "{{ myuser | default('ubuntu') }}"
  become: yes
  become_method: sudo
  roles:
    - common
    - openvpn

- hosts: dell
  remote_user: "{{ myuser | default('ubuntu') }}"
  become: yes
  become_method: sudo
  roles:
    - common
    - dell
