---
- hosts: openvpn
  become: yes
  become_method: sudo
  gather_facts: no
  pre_tasks:
    - name: install python2.7 - needed for xenial
      raw: sudo apt-get -y install python
    - name: gather facts
      setup:
  roles:
    - common
    - openvpn
