---
- include_vars: vault.yml
  no_log: true
- name: Launch instance
  ec2:
    access_key: "{{ aws_access_key }}"
    secret_key: "{{ aws_secret_key }}"
    key_name: "{{ aws_key_name }}"
    instance_type: t2.nano
    instance_tags:
      Name: AwsDocker
    image: ami-f0768de6
    region: "{{ aws_region }}"
    wait: yes
    group: ['SSH_Inbound', 'VPN_Inbound']
    count: 1
    vpc_subnet_id: "{{ aws_vpc_subnet_id }}"
    assign_public_ip: yes
