---
- include_vars: vault.yml
  no_log: true
- name: ensure packages are installed
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - acpid
    - fail2ban
    - logcheck
    - mutt
    - ntp
    - sysstat
- name: configure fail2ban
  copy:
    src: fail2ban/jail.local
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: 0644
  notify:
    - restart fail2ban
- name: enable fail2ban long term jail
  copy:
    src: fail2ban/jail.d/recidive.conf
    dest: /etc/fail2ban/jail.d/recidive.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart fail2ban
- name: configure sudo
  copy:
    content: "{{ sudoers_90_admin }}"
    dest: /etc/sudoers.d/90-admin
    owner: root
    group: root
    mode: 0440
- name: enable sysstat
  lineinfile:
    dest: /etc/default/sysstat
    regexp: ^ENABLED
    line: ENABLED=true
  notify:
    - restart sysstat
- name: add my user dwighteb
  user:
    name: dwighteb
    shell: /bin/bash
    comment: Dwight Barnette
    uid: 1100
    password: "{{ dwighteb_password }}"
    groups: adm,sudo
    append: yes
- name: authorized key file for dwighteb
  authorized_key:
    user: dwighteb
    key: https://github.com/dwighteb.keys
    exclusive: yes
- name: add my user ubuntu
  user:
    name: ubuntu
    shell: /bin/bash
    comment: ubuntu user
    password: "{{ ubuntu_password }}"
    groups: adm,sudo
    append: yes
- name: authorized key file for ubuntu
  authorized_key:
    user: ubuntu
    key: https://github.com/dwighteb.keys
- name: configure sshd
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  notify:
    - restart ssh
  with_items:
    - { regexp: '^PermitRootLogin',                 line: 'PermitRootLogin no' }
    - { regexp: '^UseDNS',                          line: 'UseDNS no' }
- name: remove user password
  user:
    name: "{{ item }}"
    password: '*'
  with_items:
    - root
    - vagrant
