---
- include_vars: vault.yml
  no_log: true

- name: ensure packages are installed
  apt:
    name: "{{ item }}"
    state: installed
    update_cache: yes
  with_items:
    - acpid
    - git
    - libpam-google-authenticator
    - ntp
    - sysstat

- name: configure sudo
  copy:
    content: "{{ sudoers_90_admin }}"
    dest: /etc/sudoers.d/90-admin
    owner: root
    group: root
    mode: 0440

- name: enable sysstat
  lineinfile:
    dest: /etc/default/sysstat
    regexp: ^ENABLED
    line: ENABLED=true
  notify:
    - restart sysstat

- name: add my user ubuntu
  user:
    name: ubuntu
    shell: /bin/bash
    comment: ubuntu user
    password: "{{ ubuntu_password }}"
    groups: adm,sudo
    append: yes

- name: authorized key file for ubuntu
  authorized_key:
    user: ubuntu
    key: '{{ item }}'
  with_file:
    - ssh_keys/db-mbp3-2016-07-09
    - ssh_keys/db-ipad-2017-02-18
    - ssh_keys/db-iphone-2017-02-18

- name: ubuntu google authenticator file
  copy:
    content: "{{ ubuntu_google_authenticator }}"
    dest: /home/ubuntu/.google_authenticator
    owner: ubuntu
    group: ubuntu
    mode: 0400

- name: configure pam.d sshd for google authenticator
  lineinfile:
    dest: /etc/pam.d/sshd
    line: 'auth required pam_google_authenticator.so'
  notify:
    - restart ssh

- name: configure sshd
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  notify:
    - restart ssh
  with_items:
    - { regexp: '^ChallengeResponseAuthentication', line: 'ChallengeResponseAuthentication yes' }
    - { regexp: '^PasswordAuthentication',          line: 'PasswordAuthentication yes' }
    - { regexp: '^PermitRootLogin',                 line: 'PermitRootLogin no' }
    - { regexp: '^UseDNS',                          line: 'UseDNS no' }
