---
# Dell tasks
- name: install role specific serverspec file
  copy: src=dell_spec.rb dest=/opt/serverspec/spec/localhost/dell_spec.rb owner=root group=root mode=0644
- name: add apt keys
  apt_key: url="{{ item }}" state=present
  with_items:
    - 'https://www.virtualbox.org/download/oracle_vbox.asc'
    - 'https://jenkins-ci.org/debian/jenkins-ci.org.key'
    - 'http://nginx.org/keys/nginx_signing.key'
- name: add apt repositories
  apt_repository: repo="{{ item }}" state=present
  with_items:
    - 'ppa:ansible/ansible'
    - 'deb http://download.virtualbox.org/virtualbox/debian trusty contrib'
    - 'deb http://pkg.jenkins-ci.org/debian-stable binary/'
    - 'deb http://nginx.org/packages/ubuntu/ trusty nginx'
- name: ensure packages are installed
  apt: name={{ item }} state=installed
  with_items:
    - anacron
    - ansible
    - apt-cacher-ng
    - git
    - jenkins
    - nginx
    - openjdk-7-jdk
    - openjdk-7-jre
    - smartmontools
    - squid-deb-proxy-client
    - virtualbox-5.0
- name: delete nginx default configuration
  file: path=/etc/nginx/conf.d/default.conf state=absent
  notify:
    - restart nginx
- name: create nginx jenkins configuration file
  copy: src=jenkins.conf dest=/etc/nginx/conf.d/jenkins.conf owner=root group=root mode=0644
- name: enable smartmontools
  lineinfile: dest=/etc/default/smartmontools regexp=^start_smartd line='start_smartd=yes'
  notify:
    - restart smartmontools
- name: Check if vagrant is installed
  command: dpkg-query -W vagrant
  register: vagrant_check_deb
  failed_when: vagrant_check_deb.rc > 1
  changed_when: vagrant_check_deb.rc == 1
- name: Download my_package
  get_url:
    url="http://releases.hashicorp.com/vagrant/1.7.4/vagrant_1.7.4_x86_64.deb"
    dest="/home/dwighteb/vagrant_1.7.4_x86_64.deb"
  when: vagrant_check_deb.rc == 1
- name: Install my_package
  apt: deb="/home/dwighteb/vagrant_1.7.4_x86_64.deb"
  sudo: true
  when: vagrant_check_deb.rc == 1
