---
- name: ensure packages are installed
  apt:
    name: "{{ item }}"
    state: installed
    update_cache: yes
  with_items:
    - anacron
    - apt-cacher-ng
    - smartmontools
    - squid-deb-proxy-client
- name: enable smartmontools
  lineinfile:
    dest: /etc/default/smartmontools
    regexp: ^start_smartd
    line: start_smartd=yes
  notify:
    - restart smartmontools
